version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: products_db
    environment:
      POSTGRES_DB: products
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    networks:
      - products_network

networks:
  products_network:
    driver: bridge

volumes:
  postgres_data: